install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flam3 freeglut3 freeglut3-dev glee-dev libavcodec-dev libavformat-dev libboost-all-dev libswscale-dev libtinyxml-dev libwxgtk3.0-dev

script:
  - ./autogen.sh
  - CPPFLAGS+=" -I/usr/include/lua5.1" ./configure --prefix=/usr
  - sed -i 's|-I /usr/include/libavutil||' MSVC/SettingsGUI/Makefile
  - make CXXFLAGS+="-DUSE_NEW_FFMPEG_API=1" GLEE_LIBS="-lGLee"

