install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq curl ffmpeg flam3 freeglut3 freeglut3-dev glee-dev libavcodec-dev libavformat-dev libavutil-dev libboost-all-dev libgtop2-dev liblua5.1-dev libswscale-dev libtinyxml-dev libwxgtk3.0-dev
  # ffmpeg preparation
  - sudo apt-get remove ffmpeg x264 libav-tools libvpx-dev libx264-dev
  - sudo apt-get -y install build-essential checkinstall git libfaac-dev libgpac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev librtmp-dev libtheora-dev libvorbis-dev pkg-config texi2html yasm zlib1g-dev
  # yasm
  - cd
  - wget http://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz
  - tar xzvf yasm-1.2.0.tar.gz
  - cd yasm-1.2.0
  - ./configure
  - make
  - sudo checkinstall --pkgname=yasm --pkgversion="1.2.0" --backup=no --deldoc=yes --fstrans=no --default
  # h264
  - cd
  - git clone --depth 1 git://git.videolan.org/x264
  - cd x264
  - ./configure --enable-static
  - make
  - sudo checkinstall --pkgname=x264 --pkgversion="3:$(./version.sh | awk -F'[" ]' '/POINT/{print $4"+git"$5}')" --backup=no --deldoc=yes --fstrans=no --default
  - cd
  # libvpx
  - git clone --depth 1 https://chromium.googlesource.com/webm/libvpx
  - cd libvpx
  - ./configure --disable-examples --disable-unit-tests
  - make
  - sudo checkinstall --pkgname=libvpx --pkgversion="1:$(date +%Y%m%d%H%M)-git" --backup=no --deldoc=yes --fstrans=no --default
  # ffmpeg
  - cd
  - git clone --depth 1 git://source.ffmpeg.org/ffmpeg
  - cd ffmpeg
  - ./configure --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-version3 --enable-x11grab
  - make
  - sudo checkinstall --pkgname=ffmpeg --pkgversion="5:$(date +%Y%m%d%H%M)-git" --backup=no --deldoc=yes --fstrans=no --default
  - hash x264 ffmpeg

script:
  - cd $TRAVIS_BUILD_DIR
  - ./autogen.sh
  - CPPFLAGS+=" -I/usr/include/lua5.1" ./configure --prefix=/usr
  - sed -i 's|-I /usr/include/libavutil||' MSVC/SettingsGUI/Makefile
  - make CXXFLAGS+="-DUSE_NEW_FFMPEG_API=1"

